# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\2022-2023大三上学习笔记\计算机网络课程设计\Mail-System\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 711)
        MainWindow.setMinimumSize(QtCore.QSize(1069, 711))
        MainWindow.setMaximumSize(QtCore.QSize(1069, 711))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../dove1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.listWidget = QtWidgets.QListWidget(MainWindow)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 171, 101))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pencil2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../inbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        self.stackedWidget = QtWidgets.QStackedWidget(MainWindow)
        self.stackedWidget.setGeometry(QtCore.QRect(200, 10, 851, 691))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageCompose = QtWidgets.QWidget()
        self.pageCompose.setObjectName("pageCompose")
        self.labelNewMail = QtWidgets.QLabel(self.pageCompose)
        self.labelNewMail.setGeometry(QtCore.QRect(10, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelNewMail.setFont(font)
        self.labelNewMail.setObjectName("labelNewMail")
        self.labelTo = QtWidgets.QLabel(self.pageCompose)
        self.labelTo.setGeometry(QtCore.QRect(10, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelTo.setFont(font)
        self.labelTo.setObjectName("labelTo")
        self.lineEditTo = QtWidgets.QLineEdit(self.pageCompose)
        self.lineEditTo.setGeometry(QtCore.QRect(90, 40, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEditTo.setFont(font)
        self.lineEditTo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditTo.setObjectName("lineEditTo")
        self.labelSubject = QtWidgets.QLabel(self.pageCompose)
        self.labelSubject.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelSubject.setFont(font)
        self.labelSubject.setObjectName("labelSubject")
        self.lineEditSubject = QtWidgets.QLineEdit(self.pageCompose)
        self.lineEditSubject.setGeometry(QtCore.QRect(90, 80, 751, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.lineEditSubject.setFont(font)
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.textEdit = QtWidgets.QTextEdit(self.pageCompose)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 831, 521))
        self.textEdit.setObjectName("textEdit")
        self.pushButtonSend = QtWidgets.QPushButton(self.pageCompose)
        self.pushButtonSend.setGeometry(QtCore.QRect(10, 650, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.pushButtonSave = QtWidgets.QPushButton(self.pageCompose)
        self.pushButtonSave.setGeometry(QtCore.QRect(100, 650, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.stackedWidget.addWidget(self.pageCompose)
        self.pageInbox = QtWidgets.QWidget()
        self.pageInbox.setObjectName("pageInbox")
        self.listWidget_2 = QtWidgets.QListWidget(self.pageInbox)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 281, 691))
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.pageInbox)
        self.verticalScrollBar.setGeometry(QtCore.QRect(260, 0, 21, 691))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.textBrowser = QtWidgets.QTextBrowser(self.pageInbox)
        self.textBrowser.setGeometry(QtCore.QRect(280, 0, 571, 691))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.pageInbox)
        self.pageContacts = QtWidgets.QWidget()
        self.pageContacts.setObjectName("pageContacts")
        self.listWidget_3 = QtWidgets.QListWidget(self.pageContacts)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 281, 691))
        self.listWidget_3.setObjectName("listWidget_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.pageContacts)
        self.textBrowser_2.setGeometry(QtCore.QRect(280, 0, 571, 691))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.pageContacts)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(260, 0, 21, 691))
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.stackedWidget.addWidget(self.pageContacts)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyMail"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Compose"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Inbox"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Drafts"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.labelNewMail.setText(_translate("MainWindow", "New Mail"))
        self.labelTo.setText(_translate("MainWindow", "To:"))
        self.labelSubject.setText(_translate("MainWindow", "Subject:"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))

