# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\2022-2023大三上学习笔记\计算机网络课程设计\Mail-System\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 711)
        MainWindow.setMinimumSize(QtCore.QSize(1069, 711))
        MainWindow.setMaximumSize(QtCore.QSize(106900, 71100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../dove1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 181, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../pencil2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../inbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 20, 821, 671))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.horizontalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageCompose = QtWidgets.QWidget()
        self.pageCompose.setObjectName("pageCompose")
        self.labelNewMail = QtWidgets.QLabel(self.pageCompose)
        self.labelNewMail.setGeometry(QtCore.QRect(10, 0, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelNewMail.setFont(font)
        self.labelNewMail.setObjectName("labelNewMail")
        self.labelTo = QtWidgets.QLabel(self.pageCompose)
        self.labelTo.setGeometry(QtCore.QRect(10, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelTo.setFont(font)
        self.labelTo.setObjectName("labelTo")
        self.lineEditTo = QtWidgets.QLineEdit(self.pageCompose)
        self.lineEditTo.setGeometry(QtCore.QRect(90, 40, 721, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEditTo.setFont(font)
        self.lineEditTo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditTo.setText("")
        self.lineEditTo.setObjectName("lineEditTo")
        self.labelSubject = QtWidgets.QLabel(self.pageCompose)
        self.labelSubject.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelSubject.setFont(font)
        self.labelSubject.setObjectName("labelSubject")
        self.lineEditSubject = QtWidgets.QLineEdit(self.pageCompose)
        self.lineEditSubject.setGeometry(QtCore.QRect(90, 80, 721, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEditSubject.setFont(font)
        self.lineEditSubject.setText("")
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.textEdit = QtWidgets.QTextEdit(self.pageCompose)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 801, 491))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButtonSend = QtWidgets.QPushButton(self.pageCompose)
        self.pushButtonSend.setGeometry(QtCore.QRect(10, 620, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.pushButtonSend.setFont(font)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.pushButtonSave = QtWidgets.QPushButton(self.pageCompose)
        self.pushButtonSave.setGeometry(QtCore.QRect(100, 620, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.stackedWidget.addWidget(self.pageCompose)
        self.pageInbox = QtWidgets.QWidget()
        self.pageInbox.setObjectName("pageInbox")
        self.listWidget_2 = QtWidgets.QListWidget(self.pageInbox)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 40, 281, 631))
        self.listWidget_2.setObjectName("listWidget_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.pageInbox)
        self.textBrowser.setGeometry(QtCore.QRect(280, 0, 541, 671))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.Reflesh_Button = QtWidgets.QPushButton(self.pageInbox)
        self.Reflesh_Button.setGeometry(QtCore.QRect(240, 0, 40, 40))
        self.Reflesh_Button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../refresh2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Reflesh_Button.setIcon(icon4)
        self.Reflesh_Button.setIconSize(QtCore.QSize(40, 40))
        self.Reflesh_Button.setObjectName("Reflesh_Button")
        self.Delete_Button = QtWidgets.QPushButton(self.pageInbox)
        self.Delete_Button.setGeometry(QtCore.QRect(770, 620, 40, 40))
        self.Delete_Button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../TRASH BIN.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete_Button.setIcon(icon5)
        self.Delete_Button.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Button.setObjectName("Delete_Button")
        self.listWidget_4 = QtWidgets.QListWidget(self.pageInbox)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 0, 281, 40))
        self.listWidget_4.setObjectName("listWidget_4")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon2)
        self.listWidget_4.addItem(item)
        self.listWidget_2.raise_()
        self.textBrowser.raise_()
        self.Delete_Button.raise_()
        self.listWidget_4.raise_()
        self.Reflesh_Button.raise_()
        self.stackedWidget.addWidget(self.pageInbox)
        self.pageContacts = QtWidgets.QWidget()
        self.pageContacts.setObjectName("pageContacts")
        self.listWidget_3 = QtWidgets.QListWidget(self.pageContacts)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 40, 281, 631))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidget_3.setFont(font)
        self.listWidget_3.setObjectName("listWidget_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.pageContacts)
        self.textBrowser_2.setGeometry(QtCore.QRect(281, 0, 541, 671))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.Resend_button = QtWidgets.QPushButton(self.pageContacts)
        self.Resend_button.setGeometry(QtCore.QRect(740, 620, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.Resend_button.setFont(font)
        self.Resend_button.setObjectName("Resend_button")
        self.listWidget_5 = QtWidgets.QListWidget(self.pageContacts)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 0, 281, 40))
        self.listWidget_5.setObjectName("listWidget_5")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setIcon(icon3)
        self.listWidget_5.addItem(item)
        self.stackedWidget.addWidget(self.pageContacts)
        self.pageEmailSent = QtWidgets.QWidget()
        self.pageEmailSent.setObjectName("pageEmailSent")
        self.label = QtWidgets.QLabel(self.pageEmailSent)
        self.label.setGeometry(QtCore.QRect(300, 100, 111, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../EmailSentIcon.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pageEmailSent)
        self.label_2.setGeometry(QtCore.QRect(300, 190, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButtonBackToInbox = QtWidgets.QPushButton(self.pageEmailSent)
        self.pushButtonBackToInbox.setGeometry(QtCore.QRect(180, 300, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButtonBackToInbox.setFont(font)
        self.pushButtonBackToInbox.setObjectName("pushButtonBackToInbox")
        self.pushButtonComposeAnotherEmail = QtWidgets.QPushButton(self.pageEmailSent)
        self.pushButtonComposeAnotherEmail.setGeometry(QtCore.QRect(360, 300, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.pushButtonComposeAnotherEmail.setFont(font)
        self.pushButtonComposeAnotherEmail.setObjectName("pushButtonComposeAnotherEmail")
        self.label_3 = QtWidgets.QLabel(self.pageEmailSent)
        self.label_3.setGeometry(QtCore.QRect(170, 250, 441, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.pageEmailSent)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listWidget, self.lineEditTo)
        MainWindow.setTabOrder(self.lineEditTo, self.lineEditSubject)
        MainWindow.setTabOrder(self.lineEditSubject, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.pushButtonSend)
        MainWindow.setTabOrder(self.pushButtonSend, self.pushButtonSave)
        MainWindow.setTabOrder(self.pushButtonSave, self.listWidget_4)
        MainWindow.setTabOrder(self.listWidget_4, self.Reflesh_Button)
        MainWindow.setTabOrder(self.Reflesh_Button, self.listWidget_2)
        MainWindow.setTabOrder(self.listWidget_2, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.Delete_Button)
        MainWindow.setTabOrder(self.Delete_Button, self.listWidget_3)
        MainWindow.setTabOrder(self.listWidget_3, self.textBrowser_2)
        MainWindow.setTabOrder(self.textBrowser_2, self.Resend_button)
        MainWindow.setTabOrder(self.Resend_button, self.pushButtonBackToInbox)
        MainWindow.setTabOrder(self.pushButtonBackToInbox, self.pushButtonComposeAnotherEmail)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EasyMail"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Compose"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Inbox"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Drafts"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.labelNewMail.setText(_translate("MainWindow", "New Mail"))
        self.labelTo.setText(_translate("MainWindow", "To:"))
        self.labelSubject.setText(_translate("MainWindow", "Subject:"))
        self.pushButtonSend.setText(_translate("MainWindow", "Send"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        __sortingEnabled = self.listWidget_4.isSortingEnabled()
        self.listWidget_4.setSortingEnabled(False)
        item = self.listWidget_4.item(0)
        item.setText(_translate("MainWindow", "Inbox"))
        self.listWidget_4.setSortingEnabled(__sortingEnabled)
        self.Resend_button.setText(_translate("MainWindow", "Send"))
        __sortingEnabled = self.listWidget_5.isSortingEnabled()
        self.listWidget_5.setSortingEnabled(False)
        item = self.listWidget_5.item(0)
        item.setText(_translate("MainWindow", "Drafts"))
        self.listWidget_5.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Email Sent"))
        self.pushButtonBackToInbox.setText(_translate("MainWindow", "Back to Inbox"))
        self.pushButtonComposeAnotherEmail.setText(_translate("MainWindow", "Compose another email"))
        self.label_3.setText(_translate("MainWindow", "The email is sent and has been saved to the \"Sent\" folder"))

